Controllers/userController.cs
using dotnet_mvc.Models;
using FluentValidation.Results;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using WebApi.Models;

 namespace dotnet_mvc.Controllers
 {
     public class userController : Controller
     {
        public IActionResult namePage()//View cadastro de nome.
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> namePage([Bind("name")] nameViewModel user)
        {
            using (var pgsql = new npgsqlCon())
            if (ModelState.IsValid)
            {
                user.uuId = Guid.NewGuid().ToString(user.uuId);
                HttpContext.Session.SetString("name", user.name);
                return RedirectToAction(nameof(companyPage));
            }
            return View(user);
        }
//--------------------------------------------------------------------------------------------------------
        public IActionResult companyPage()//View cadastro do nome da empresa.
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> companyPage([Bind("companyName")] companyViewModel user)
        {
            using (var pgsql = new npgsqlCon())
            if (ModelState.IsValid)
            {
                HttpContext.Session.SetString("companyName", user.companyName);
                return RedirectToAction(nameof(documentPage));
            }
            return View(user);
        }
//----------------------------------------------------------------------------------------------------------
        public IActionResult documentPage()//View cadastro do documento.
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> documentPage([Bind("cpf, cnpj")] documnetViewModel user)
        {
            using (var pgsql = new npgsqlCon())
            if (ModelState.IsValid)
            {
                //user = pgsql.FindAsync(userId);
                //user.companyName = "nome da empresa";
                //pgsql.(user);pgsql.modify
                //pgsql.Add(user);
                //await pgsql.SaveChangesAsync();
                HttpContext.Session.SetString("cpf", user.cpf);
                return RedirectToAction(nameof(phonePage));
            }
            return View(user);
        }
//--------------------------------------------------------------------------------------------------------
        public IActionResult phonePage()//View cadastro do telefone.
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> phonePage([Bind("phoneNumber")] phoneViewModel user)
        {
            using (var pgsql = new npgsqlCon())
            if (ModelState.IsValid)
            {
                //user = pgsql.FindAsync(userId);
                //user.companyName = "nome da empresa";
                //pgsql.(user);pgsql.modify
                //pgsql.Add(user);
                //await pgsql.SaveChangesAsync();
                HttpContext.Session.SetString("phoneNumber", user.phoneNumber);
                return RedirectToAction(nameof(emailPage));
            }
            return View(user);
        }
//--------------------------------------------------------------------------------------------------------
        public IActionResult emailPage()//View cadastro do email.
        {
            return View();
        }
        [HttpPost]
            public async Task<IActionResult> emailPage([Bind("email")] emailViewModel user)
        {
            using (var pgsql = new npgsqlCon())
            if (ModelState.IsValid)
            {
                //user = pgsql.FindAsync(userId);
                //user.companyName = "nome da empresa";
                //pgsql.(user);pgsql.modify
                //pgsql.Add(user);
                //await pgsql.SaveChangesAsync();
                HttpContext.Session.SetString("email", user.email);
                return RedirectToAction(nameof(passwordPage));
            }
            return View(user);
        }
//--------------------------------------------------------------------------------------------------------

         public IActionResult passwordPage()//View cadastro da senha.
        {
            return View();
        }
            [HttpPost]
            public async Task<IActionResult> passwordPage([Bind("password")] passwordViewModel user)
        {
            using (var pgsql = new npgsqlCon())
            if (ModelState.IsValid)
            {
                //user = pgsql.FindAsync(userId);
                //user.companyName = "nome da empresa";
                //pgsql.(user);pgsql.modify
                //pgsql.Add(user);
                //await pgsql.SaveChangesAsync();
                user.password = BCrypt.Net.BCrypt.HashPassword(user.password);//Encripta a senha do usuário.
                HttpContext.Session.SetString("password", user.password);
                return RedirectToAction(nameof(cepPage));            
            }
            return View(user);
        }
//--------------------------------------------------------------------------------------------------------
        public IActionResult cepPage()//View cadastro do enfereço.
        {
            return View();
        }
        public IActionResult homePage()
        {
            return View();
        }

            [HttpPost]
            public async Task<IActionResult> cepPage([Bind("cep, state, city, district, street, number, complement")] cepViewModel user)
        {
            using (var pgsql = new npgsqlCon())
            if (ModelState.IsValid)
            {
                //user = pgsql.FindAsync(userId);
                //user.companyName = "nome da empresa";
                //pgsql.(user);pgsql.modify
                //pgsql.Add(user);
                //await pgsql.SaveChangesAsync();
                HttpContext.Session.SetString("cep", user.cep);
                await pgsql.SaveChangesAsync();
                return RedirectToAction(nameof(homePage));
            }
            return View(user);
        }
     }
 }
 //--------------------------------------------------------------------------------------------------------

        //SALVAR USUÁRIO 
        // [HttpPost]
        // public static async Task<string> SaveUser([FromBody]User user)
        // {
        //     string response = "";
        //     userValidator validator = new userValidator();
        //     ValidationResult result = validator.Validate(user);//Faz a validação do usuário.
        //     string message = result.ToString();
        //     if (!result.IsValid)
        //     {
        //         return message;
        //     }
        //     else
        //     {
        //         using (var pgsql = new npgsqlCon())//Utilizar o banco de dados.
        //         {
        //             try
        //             {
        //                 List<User> IsEmailValid = pgsql.Users.Where(x => x.email == user.email).ToList();//Verifica se o email já existe no banco.                                                    
        //                 if (IsEmailValid.Count == 0)
        //                 {//Persiste o usuário, caso ele não esteja na base.
        //                     List<User> IsDocumentValid = pgsql.Users.Where(x => x.cpf == user.cpf).Where(x => x.cnpj == user.cnpj).ToList();//Verifica se os documentos já existem no banco.
        //                     if (IsDocumentValid.Count == 0)
        //                     {
        //                         user.uuId = Guid.NewGuid().ToString(user.uuId);//Gera o uuId do usuário.
        //                         user.password = BCrypt.Net.BCrypt.HashPassword(user.password);//Encripta a senha do usuário.
        //                         user.email = user.email.ToString().ToLower();//Salva o email no banco em lower case.
        //                         pgsql.Users.Add(user);
        //                         await pgsql.SaveChangesAsync();
        //                         message = "OK";//Usuário salvo com sucesso.
        //                         response = JsonSerializer.Serialize(new { user.userId, user.uuId, message });//Retorno para o front.
        //                     }
        //                     else
        //                     {
        //                         message = "DOCUMENT_EXISTS";//Cpf ou Cnpj já existente no banco.
        //                         response = JsonSerializer.Serialize(new { message });
        //                     }
        //                 }
        //                 else
        //                 {
        //                     message = "EMAIL_EXISTS";//Email já existente no banco.
        //                     response = JsonSerializer.Serialize(new { message });
        //                 }
        //             }
        //             catch (Exception e)
        //             {
        //                 Console.WriteLine(e.ToString());
        //             }
        //             return response;
        //         }
        //     }
        // }

        //EDITAR USUÁRIO 
//         [HttpPut("/edituser/{Id}")]
//         public static async Task<String> EditUser([FromBody] User user)//Passar o id e uuId para edição.
//         {
//             string response = "";
//             string message = response.ToString();
//             using (var pgsql = new npgsqlCon())
//             {
//                 try
//                 {
//                     var users = new User();
//                     pgsql.Users.Update(user);//Edita um usuário existente no bacno.
//                     await pgsql.SaveChangesAsync();
//                     message = "OK";//Usuário editado com sucesso.
//                     response = JsonSerializer.Serialize(new { message });
//                 }
//                 catch (Exception e)
//                 {

Views/user/cepPage.cshtml
@model cepViewModel;
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/register.css">
  <title>Cadastro!</title>
</head>
<body>
  <a href="@Url.Action("passwordPage", "user")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <h1 class="nameTextPass">Para finalizar o cadastro, nos informe sua localização.</h1>
  <div class="input-label-pass">
  @Html.TextBox("cep", null, new {placeholder = "CEP", @class = "cepBox", id="buscarCep"})
  @Html.ValidationMessageFor(user => user.uf, "", new { @class = "error-text"})
  </div>
  @using (Html.BeginForm("cepPage","user", FormMethod.Post))
  {
    <div class="input-label-pass">
    @Html.TextBox("Estado", null, new {placeholder = "Estado", @class = "input-text-desc"})
    @Html.ValidationMessageFor(user => user.uf, "", new { @class = "error-text"})

    @Html.TextBox("Cidade", null, new {placeholder = "Cidade", @class = "input-text-desc"})
    @Html.ValidationMessageFor(user => user.city, "", new { @class = "error-text"})

    @Html.TextBox("Bairro", null, new {placeholder = "Bairro", @class = "input-text-desc"})
    @Html.ValidationMessageFor(user => user.district, "", new { @class = "error-text"})

    @Html.TextBox("Rua", null, new {placeholder = "Rua", @class = "input-text-desc"})
    @Html.ValidationMessageFor(user => user.street, "", new { @class = "error-text"})

    @Html.TextBox("Num", null, new {placeholder = "Número da residência", @class = "input-text-desc"})
    @Html.ValidationMessageFor(user => user.number, "", new { @class = "error-text"})
    
    @Html.TextBox("Comp", null, new {placeholder = "Complemento", @class = "input-text-desc"})
    @Html.ValidationMessageFor(user => user.complement, "", new { @class = "error-text"})
    </div>
    <input type="submit" value="Continuar" class="button">
  }
</body>
</html>

Views/user/companyPage.cshtml
@model companyViewModel;
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/register.css">
  <title>Cadastro!</title>
</head>
<body>
  <a href="@Url.Action("namePage", "user")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <h1 class="nameText">Digite o nome que você gostaria que fosse mostrado para seus clientes.</h1>
    @using (Html.BeginForm("companyPage","user", FormMethod.Post))
  {
    <div class="input-label-company">
      @Html.LabelFor(model => model.companyName)
      @Html.TextBoxFor(model => model.companyName, new {@class = "input-company"})
      @Html.ValidationMessageFor(user => user.companyName, "", new { @class = "error-text"})
    </div>
   <input type="submit" value="Continuar" class="button">
  }
</body>
</html>

Views/user/documentPage.cshtml
@model documnetViewModel;
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/register.css">
  <title>Cadastro!</title>
</head>
<body>
  <a href="@Url.Action("companyPage", "user")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <h1 class="nameText">Informe um cpf ou cnpj que gostaria de usar.</h1>
      @using (Html.BeginForm("documentPage","user", FormMethod.Post))
  {
    <div class="input-label-document">
      @Html.LabelFor(model => model.cpf)
      @Html.TextBoxFor(model => model.cpf, new {@class = "input-document"})
      @Html.ValidationMessageFor(user => user.cpf, "", new { @class = "error-text"})
    </div>
    <input type="submit" value="Continuar" class="button">
  }
</body>
</html>

Views/user/emailPage.cshtml
@model emailViewModel;
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/register.css">
  <title>Cadastro!</title>
</head>
<body>
  <a href="@Url.Action("phonePage", "user")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <h1 class="nameTextEmail">Digite um email para acessar sua conta.</h1>
    @using (Html.BeginForm("emailPage","user", FormMethod.Post))
  {
    <div class="input-label-email">
      @Html.LabelFor(model => model.email)
      @Html.TextBoxFor(model => model.email, new {@class = "input-text-email"})
      @Html.ValidationMessageFor(user => user.email, "", new { @class = "error-text"})
    </div>
    <input type="submit" value="Continuar" class="button">
  }
</body>
</html>

Views/user/namePage.cshtml
@model nameViewModel; 
@using Microsoft.AspNetCore.Components
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/register.css">
  <title>Cadastro!</title>
</head>
<body>
  <a href="@Url.Action("Index", "Home")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <h1 class="nameText">Digite seu nome para que possamos te identificar.</h1>
  @using (Html.BeginForm("namePage","user", FormMethod.Post))
  {
    <div class="input-label">
      @Html.LabelFor(model => model.name)
      @Html.TextBoxFor(model => model.name, new {@class = "input-text"})
      @Html.ValidationMessageFor(user => user.name, "", new { @class = "error-text"})
    </div>
    <input type="submit" value="Continuar" class="button">
  }
</body>
</html>

Views/user/passwordPage.cshtml
@model passwordViewModel;
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/register.css">
  <title>Cadastro!</title>
</head>
<body>
  <a href="@Url.Action("emailPage", "user")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <h1 class="nameTextPass">Para a segurança da sua conta, crie uma senha forte.</h1>
      @using (Html.BeginForm("passwordPage","user", FormMethod.Post))
  {
    <div class="input-label-pass">
      @Html.LabelFor(model => model.password)
      @Html.TextBoxFor(model => model.password, new {@class = "input-text-pass"})
      @Html.ValidationMessageFor(user => user.password, "", new { @class = "error-text"})
    </div>
    <ul class="pass">
      <li>Pelo menos 8 caracteres</li>
      <li>Pelo menos 1 letra maiúscula</li>
      <li>Pelo menos 1 letra minúscula</li>
      <li>Pelo menos 1 número</li>
      <li>Pelo menos 1 caractere especial (#, $, etc.)</li>
    </ul>
      <input type="submit" value="Continuar" class="button">
  }
</body>
</html>

Views/user/phonePage.cshtml
@model phoneViewModel;
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/register.css">
  <title>Cadastro!</title>
</head>
<body>
  <a href="@Url.Action("documentPage", "user")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <h1 class="nameText">Digite um número de telefone para contato.</h1>
    @using (Html.BeginForm("phonePage","user", FormMethod.Post))
  {
    <div class="input-label-phone">
      @Html.LabelFor(model => model.phoneNumber)
      @Html.TextBoxFor(model => model.phoneNumber, new {@class = "input-text-phone"})
      @Html.ValidationMessageFor(user => user.phoneNumber, "", new { @class = "error-text"})
    </div>
    <input type="submit" value="Continuar" class="button">
  }
</body>
</html>