Controllers/productController.cs
using dotnet_mvc.Models;
using FluentValidation.Results;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using WebApi.Models;

 namespace dotnet_mvc.productControllers
 {
     public class productController : Controller
     {
        public IActionResult homePage()
        {
            return View();
        }

        // [ViewComponent] //TESTE 
        // public class Footer : ViewComponent
        // {
        //     public async Task<IViewComponentResult> InvokeAsync()
        //     {
        //     return View();
        //     }
        // }
        
        [HttpPost]
        public async Task<IActionResult> homePage(productViewModel product)
        {
            using (var pgsql = new npgsqlCon())
            return RedirectToAction(nameof(registerProductPage));
        }
        public IActionResult registerProductPage()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> registerProductPage(productViewModel product)
        {
            using (var pgsql = new npgsqlCon())     
            return RedirectToAction(nameof(homePage));
        }
     }
 }

Views/product/homePage.cshtml
@model productViewModel; 
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home Page</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="/css/product.css">
    <script src='main.js'></script>
</head>
<body>
    <div class="icon-container"></div>
    <a href="@Url.Action("Index", "Home")" class="arrowButton">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  <div>
    <p class="produtos-text">Produtos</p>
  </div>
    @using (Html.BeginForm("homePage","product", FormMethod.Post))
    {
      <input type="submit" value="Novo produto" class="button">
    }
    @* @await Component.InvokeAsync("Default", Model); *@
</body>
</html> 

Views/product/registerProductPage.cshtml
@model Product; 
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home Page</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="/css/product.css">
    <script src='main.js'></script>
</head>
<body>
    <div class="icon-container">
    <a href="@Url.Action("homePage", "product")" class="arrowButton-Register">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left"
      viewBox="0 0 16 16">
      <path fill-rule="evenodd"
        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
    </svg>
  </a>
  </div>
  <div>
    <p class="text">Novo produto</p>
  </div>
  <div class="first-card">
    <div class="card">  
    <div class="card-body">
      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi-camera" viewBox="0 0 16 16">
    <path d="M15 12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h1.172a3 3 0 0 0 2.12-.879l.83-.828A1 1 0 0 1 6.827 3h2.344a1 1 0 0 1 .707.293l.828.828A3 3 0 0 0 12.828 5H14a1 1 0 0 1 1 1v6zM2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2z"/>
    <path d="M8 11a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
    </svg>
  </div>
</div>
<div class="card">  
    <div class="card-body">
      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi-camera" viewBox="0 0 16 16">
    <path d="M15 12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h1.172a3 3 0 0 0 2.12-.879l.83-.828A1 1 0 0 1 6.827 3h2.344a1 1 0 0 1 .707.293l.828.828A3 3 0 0 0 12.828 5H14a1 1 0 0 1 1 1v6zM2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2z"/>
    <path d="M8 11a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
    </svg>
  </div>
</div>
<div class="card">
    <div class="card-body">
      <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi-camera" viewBox="0 0 16 16">
    <path d="M15 12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h1.172a3 3 0 0 0 2.12-.879l.83-.828A1 1 0 0 1 6.827 3h2.344a1 1 0 0 1 .707.293l.828.828A3 3 0 0 0 12.828 5H14a1 1 0 0 1 1 1v6zM2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2z"/>
    <path d="M8 11a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7zM3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
    </svg>
  </div>
</div>
</div>
<div class="cat">
<p>Selecione a categoria do produto</p>
</div>
<div class="cat-box">
  <select class="cat-select">
    <option value="Cat1">Cat1</option>
    <option value="Cat2">Cat2</option>
    <option value="Cat3">Cat3</option>
  </select>
  </div>
  <div class="input-label">
      @Html.LabelFor(model => model.name)
      @Html.TextBoxFor(model => model.name, new {@class = "input-text"})
      @Html.ValidationMessageFor(user => user.name, "", new { @class = "error-text"})
    </div>
     <div class="input-label">
      @Html.LabelFor(model => model.description)
      @Html.TextBoxFor(model => model.description, new {@class = "input-text"})
      @Html.ValidationMessageFor(user => user.description, "", new { @class = "error-text"})
    </div>
     <div class="input-label">
      @Html.LabelFor(model => model.price)
      @Html.TextBoxFor(model => model.price, new {@class = "input-text"})
      @Html.ValidationMessageFor(user => user.price, "", new { @class = "error-text"})
    </div> 
<div class="sw-class">
    <label class="switch">
        <input type="checkbox">
        <span class="slider round"></span>
    </label>
</div>
    @using (Html.BeginForm("registerProductPage","product", FormMethod.Post))
    {
      <input type="submit" value="Cadastrar produto" class="button">
    }
</body>
</html>
 